BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"username"	TEXT NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"surname"	TEXT NOT NULL,
	"classe"	TEXT NOT NULL,
	"email"	TEXT NOT NULL UNIQUE,
	"passwordHash"	TEXT NOT NULL,
	"token"	TEXT NOT NULL,
	"imgUrl"	TEXT,
	"lastEdit"	INTEGER,
	"created"	INTEGER,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "Descriptors" (
	"id"	INTEGER NOT NULL UNIQUE,
	"authorId"	INTEGER,
	"title"	TEXT NOT NULL,
	"description"	TEXT NOT NULL,
	"delta"	INTEGER NOT NULL,
	"lastEdit"	INTEGER,
	"created"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "DescriptorRecords" (
	"id"	INTEGER NOT NULL UNIQUE,
	"gameId"	INTEGER NOT NULL,
	"profId"	INTEGER NOT NULL,
	"descriptorId"	INTEGER NOT NULL,
	"instant"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Games" (
	"id"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL,
	"description"	INTEGER,
	"gameMasterId"	INTEGER NOT NULL,
	"maxBettableProfs"	INTEGER DEFAULT 2,
	"start"	INTEGER NOT NULL,
	"end"	INTEGER NOT NULL,
	"professorIds"	TEXT NOT NULL,
	"descriptorIds"	TEXT NOT NULL,
	"lastEdit"	INTEGER,
	"created"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Professors" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"surname"	TEXT NOT NULL,
	"lastEdit"	INTEGER,
	"created"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "SNAICards" (
	"id"	INTEGER NOT NULL UNIQUE,
	"userId"	INTEGER NOT NULL,
	"gameId"	INTEGER NOT NULL,
	"bettedProfIds"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
