BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Users";
CREATE TABLE IF NOT EXISTS "Users" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"username"	TEXT NOT NULL,
	"name"	INTEGER NOT NULL,
	"surname"	INTEGER NOT NULL,
	"classe"	TEXT NOT NULL,
	"email"	INTEGER NOT NULL,
	"passwordHash"	TEXT NOT NULL,
	"token"	TEXT NOT NULL,
	"imgUrl"	TEXT,
	"lastEdit"	INTEGER,
	"created"	INTEGER
);
DROP TABLE IF EXISTS "DescriptorsRecords";
CREATE TABLE IF NOT EXISTS "DescriptorsRecords" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"gameId"	INTEGER NOT NULL,
	"profId"	INTEGER NOT NULL,
	"descriptorId"	INTEGER NOT NULL,
	"instant"	INTEGER NOT NULL
);
DROP TABLE IF EXISTS "Game";
CREATE TABLE IF NOT EXISTS "Game" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"title"	TEXT NOT NULL,
	"description"	INTEGER,
	"gameMasterId"	INTEGER NOT NULL,
	"maxBettableProfs"	INTEGER DEFAULT 2,
	"start"	INTEGER NOT NULL,
	"end"	INTEGER NOT NULL,
	"professorIds"	TEXT NOT NULL,
	"descriptorIds"	TEXT NOT NULL
);
DROP TABLE IF EXISTS "Professors";
CREATE TABLE IF NOT EXISTS "Professors" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"surname"	TEXT NOT NULL
);
DROP TABLE IF EXISTS "Descriptors";
CREATE TABLE IF NOT EXISTS "Descriptors" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"title"	TEXT NOT NULL,
	"description"	TEXT NOT NULL,
	"delta"	INTEGER NOT NULL
);
DROP TABLE IF EXISTS "SNAICards";
CREATE TABLE IF NOT EXISTS "SNAICards" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"userId"	INTEGER NOT NULL,
	"gameId"	INTEGER NOT NULL,
	"bettedProfsIds"	TEXT
);
COMMIT;
